#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height) return;

    float2 fragCoord = float2(id.x, id.y);
    float2 iResolution = float2(m_width, m_height);
    float2 uv = fragCoord / iResolution;

    float3 col = m_source[id.xy].rgb;

    float3x3 blowout = float3x3(
        1.87583893, 0.96308725, 0.0,
        0.96308725, 1.17416107, 0.0,
        0.0,        0.0,        0.5
    );
    float3 cent = float3(0.47968451, 0.450743, 0.45227517);

    float3 dir = mul(blowout, (col - cent));

    float3 maxes = (step(float3(0.0, 0.0, 0.0), dir) - col) / max(dir, float3(1e-6, 1e-6, 1e-6));

    float amount = max(maxes.x, max(maxes.y, maxes.z));


    float weight = 1.0;
    amount = saturate(amount);


    col = col + dir * weight * amount;
    col = saturate(col);

    m_result[id.xy] = float4(col, 1.0);
}
