#pragma kernel CSMain

// Input & output textures
RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

// Crop parameters in pixels
int cropX;
int cropY;
int cropWidth;
int cropHeight;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= cropWidth || id.y >= cropHeight)
        return;
    
    int2 srcPos = int2(cropX + id.x, cropY + id.y);
    float4 color = m_source[srcPos];
    color.a = 1.0f;
    m_result[int2(id.x, id.y)] = color;
}
