//https://www.shadertoy.com/view/lcfXWB
#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;

    int par = (id.x + id.y) % 2;
    float2 uv = float2(id.x, id.y) / float2(m_width, m_height);
    float4 c = m_source[id.xy];

    float4 fragColor;

    if (par == 0)
    {
        fragColor = float4(0.299 * c.r, 0.0, 0.0, 0.0);
    }
    else
    {
        float luma = 0.299 * c.r + 0.587 * c.g + 0.114 * c.b;
        fragColor = float4(luma, luma, luma, 0.0);
    }
    fragColor.a = 1;
    m_result[id.xy] = fragColor;
}