#pragma kernel CSMain
#define BLACK_THRESHOLD 0.25


RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;
int m_width;
int m_height;
int m_pixelCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;

    float4 color = m_source[id.xy];
    bool isBlack = (abs(color.r) <= BLACK_THRESHOLD) &&
                   (abs(color.g) <= BLACK_THRESHOLD) &&
                   (abs(color.b) <= BLACK_THRESHOLD);
    m_result[id.xy] = isBlack ? color : float4(1,1,1, 0);
}
