// Main compute shader kernel
#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;


[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;
    
    int halfWidth = m_width / 2;
   
    int srcX = id.x < halfWidth ? id.x : m_width - id.x - 1;
    float4 color = m_source[int2(srcX, id.y)];

    m_result[id.xy] = color;
}