#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;

    float2 fragCoord = float2(id.x, id.y);
    float2 uv = fragCoord / float2(m_width, m_height);

    float4 texColor = m_source[id.xy];
    float3 col = texColor.rgb;

   
        col = float3(pow(col.r, 7.0/5.0), col.g, pow(col.b, 8.0/5.0));
   
        //col = float3(pow(col.r, 1.3), pow(col.g, 1.3), col.b * 0.6);
    

    m_result[id.xy] = float4(col, 1.0);
}