// Main compute shader kernel
#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;
    
    int halfHeight = m_height / 2;
    
    int srcY = id.y < halfHeight ? m_height - id.y - 1 : id.y;
   
    float4 color = m_source[int2(id.x, srcY)];

    m_result[id.xy] = color;
}