#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;
int m_width;
int m_height;
int m_pixelCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;
    
    float4 srcColor = m_source[id.xy];
    
    // Remove green channel
    float4 color = float4(0, srcColor.g, 0, srcColor.a);
    
    m_result[id.xy] = color;
}
