#pragma kernel CSMain

RWTexture2D<uint4> m_source;
RWTexture2D<uint4> m_result;
int m_width;
int m_height;
int m_pixelCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;

    int2 flippedCoord = int2(
        m_width - 1 - id.x,
        id.y
    );

    float4 color = m_source.Load(int3(flippedCoord, 0));
    m_result[id.xy] = color;
}
