#pragma kernel CSMain

#define MAGENTA_RED_OUT_THRESHOLD 0.5
#define MAGENTA_BLUE_OUT_THRESHOLD 0.5

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;
int m_width;
int m_height;
int m_pixelCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;
    
    float4 srcColor = m_source[id.xy];
    
    // Remove green channel
    float4 color = float4(1-srcColor.r, 0.0, 1-srcColor.b, srcColor.a);
    
    if (color.r > MAGENTA_RED_OUT_THRESHOLD || color.b < MAGENTA_BLUE_OUT_THRESHOLD)
    {
        
        m_result[id.xy] = float4(1,1,1, 1);
        return;
    }
    
    m_result[id.xy] = color;
}
