#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;
int m_width;
int m_height;
int m_pixelCount;


[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;
    
    float4 color = m_source[id.xy];

    if (color.x > 0.95 && color.y > 0.95 && color.z > 0.95)
    
        m_result[id.xy] = color;
    
    else
    m_result[id.xy] = float4(0, 0, 0, 0);
}
