#pragma kernel CSMain

RWTexture2D<float4> m_source;
RWTexture2D<float4> m_result;

int m_width;
int m_height;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= m_width || id.y >= m_height)
        return;

    bool linhaPar = (id.y % 2) == 0;
    float2 uv = float2(id.x, id.y) / float2(m_width, m_height);
    float4 c = m_source[id.xy];
    float4 fragColor;

    if (linhaPar)
    {
        float value = 0.2 * c.r + 0.7 * c.g + 0.1 * c.b;
        fragColor = float4(value, value, value, 1.0);
    }
    else
    {
        fragColor = float4(c.r, 0.0, 0.0, 0.0);
        fragColor.a = 1.0;
    }

    m_result[id.xy] = fragColor;
}